apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: artifactory-application-set
spec:
  generators:
    - git:
        repoURL: 'https://github.com/orgv/devtools-definition.git'
        revision: HEAD
        directories:
          - path: 'artifactory/values/*'
  template:
    metadata:
      name: 'artifactory-{{path.basename}}' 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/orgv/devtools-provision.git'
        path: 'wrapper-artifactory'
        helm:
          valueFiles:
            - 'https://raw.githubusercontent.com/orgv/devtools-definition/main/{{path}}/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'artifactory-{{path.basename}}'
